declare namespace Server {
  // TODO: attachElements
  // TODO: clearElementVisibleTo
  // TODO: cloneElement
  // TODO: createElement
  // TODO: destroyElement
  // TODO: detachElements
  // TODO: getAllElementData
  // TODO: getAttachedElements
  // TODO: getElementAlpha
  // TODO: getElementAttachedOffsets
  // TODO: getElementAttachedTo
  // TODO: getElementCollisionsEnabled
  // TODO: getElementByID
  // TODO: getElementByIndex
  // TODO: getElementChild
  // TODO: getElementChildren
  // TODO: getElementChildrenCount
  // TODO: getElementColShape
  // TODO: getElementData
  // TODO: getElementDimension
  // TODO: getElementHealth
  // TODO: getElementID
  // TODO: getElementInterior
  // TODO: getElementMatrix
  // TODO: getElementModel
  // TODO: getElementParent
  // TODO: getElementPosition
  // TODO: getElementRotation
  // TODO: getElementSyncer
  // TODO: getElementType
  // TODO: getElementVelocity
  // TODO: getElementZoneName
  // TODO: getElementsByType
  // TODO: getElementsWithinColShape
  // TODO: getLowLODElement
  // TODO: getRootElement
  // TODO: isElement
  // TODO: isElementAttached
  // TODO: isElementCallPropagationEnabled
  // TODO: isElementDoubleSided
  // TODO: isElementFrozen
  // TODO: isElementInWater
  // TODO: isElementLowLOD
  // TODO: isElementVisibleTo
  // TODO: isElementWithinColShape
  // TODO: isElementWithinMarker
  // TODO: removeElementData
  // TODO: setElementAlpha
  // TODO: setElementAngularVelocity
  // TODO: getElementAngularVelocity
  // TODO: setElementAttachedOffsets
  // TODO: setElementCallPropagationEnabled
  // TODO: setElementCollisionsEnabled
  // TODO: setElementData
  // TODO: setElementDimension
  // TODO: setElementDoubleSided
  // TODO: setElementFrozen
  // TODO: setElementHealth
  // TODO: setElementID
  // TODO: setElementInterior
  // TODO: setElementModel
  // TODO: setElementParent
  // TODO: setElementPosition
  // TODO: setElementRotation
  // TODO: setElementSyncer
  // TODO: setElementVelocity
  // TODO: setElementVisibleTo
  // TODO: setLowLODElement
}