declare namespace Client {
  // TODO: attachElements
  // TODO: createElement
  // TODO: destroyElement
  // TODO: detachElements
  // TODO: getAttachedElements
  // TODO: getElementAlpha
  // TODO: getElementAttachedOffsets
  // TODO: getElementAttachedTo
  // TODO: getElementBoundingBox
  // TODO: getElementByID
  // TODO: getElementChild
  // TODO: getElementChildren
  // TODO: getElementChildrenCount
  // TODO: getElementColShape
  // TODO: getElementCollisionsEnabled
  // TODO: getElementData
  // TODO: getElementDimension
  // TODO: getElementDistanceFromCentreOfMassToBaseOfModel
  // TODO: getElementHealth
  // TODO: getElementID
  // TODO: getElementInterior
  // TODO: getElementMatrix
  // TODO: getElementModel
  // TODO: getElementParent
  // TODO: getElementPosition
  // TODO: getElementRadius
  // TODO: getElementRotation
  // TODO: getElementType
  // TODO: getElementVelocity
  // TODO: getElementsByType
  // TODO: getElementsWithinColShape
  // TODO: getElementsWithinRange
  // TODO: getLowLODElement
  // TODO: getRootElement
  // TODO: isElement
  // TODO: isElementAttached
  // TODO: isElementCallPropagationEnabled
  // TODO: isElementCollidableWith
  // TODO: isElementDoubleSided
  // TODO: isElementFrozen
  // TODO: isElementInWater
  // TODO: isElementLocal
  // TODO: isElementLowLOD
  // TODO: isElementOnScreen
  // TODO: isElementStreamable
  // TODO: isElementStreamedIn
  // TODO: isElementSyncer
  // TODO: isElementWaitingForGroundToLoad
  // TODO: isElementWithinColShape
  // TODO: setElementAlpha
  // TODO: setElementAngularVelocity
  // TODO: getElementAngularVelocity
  // TODO: setElementAttachedOffsets
  // TODO: setElementCallPropagationEnabled
  // TODO: setElementCollidableWith
  // TODO: setElementCollisionsEnabled
  // TODO: setElementData
  // TODO: setElementDimension
  // TODO: setElementDoubleSided
  // TODO: setElementFrozen
  // TODO: setElementHealth
  // TODO: setElementID
  // TODO: setElementInterior
  // TODO: setElementMatrix
  // TODO: setElementModel
  // TODO: setElementParent
  // TODO: setElementPosition
  // TODO: setElementRotation
  // TODO: setElementStreamable
  // TODO: setElementVelocity
  // TODO: setLowLODElement
}